### ISSUE TITLE
Union queries not working with parallel parser

### ISSUE THREAD

**Issue by yenda** [wilkerlucio/pathom#160] opened 2020-05-17 12:33 UTC
the union-query example from the docs (https://cljdoc.org/d/com.wsscode/pathom/2.3.0-alpha6/doc/pathom-developers-guide#_union_queries) works with a `parser` but not with a `parallel-parser` or `async-parser`:

async-parser: 
```{:search [{} {} {}]}```
parallel-parser: 
```{:search []}```
parser: 
```{:search [{:user/name Jack Sparrow} {:movie/title Ted} {:book/title The Joy of ...```

So far the only solution I found was to make add a `::p/reader`, specify `::p/union-path` as a function instead of a keyword and redefine `join-seq-parallel` so that it doesn't return just `[]` when the query is not a vector (a union query would be a map):

```
(def user-notifications
  {:user/notifications
   (fn [env]
     (go-catch
        (<! (join-seq-parallel (assoc env
                                      ::p/union-path
                                      (fn [{:keys [query] :as env}]
                                        (let [e (p/entity env)]
                                          (:notification/type e))))
                               n)))))})
```

So as far as I understand to fix this in the lib I think:
- join-seq-parallel should also work when the query is a map if it's a union query
- union-path should work when it's a keyword

Also I don't see an obvious way to get it to work with a regular pathom.connect resolver, when I tried using the code above in a defresolver it would just return `[]`. Maybe the simplest solution from an api pov would be that defresolver takes ::p/union-path as an option?

**Comment by wilkerlucio** [comment] 2020-05-17 20:14
Fixed by #161

**Closed by wilkerlucio** 2020-05-17 20:14 UTC

**Comment by tmoerman** [comment] 2020-10-18 21:06
I'm not sure this is fixed:

My query:
`
(parse-result [{[:nexus.input-group/id 1] [{:nexus.input-group/cases-union {:nexus.case.image-annotation/id [:nexus.case.test-case/id
                                                                                                                   :cmmn.case/id
                                                                                                                   :cmmn.case/name]
                                                                                  :nexus.case.test-case/id        [:nexus.case.test-case/id
                                                                                                                   :cmmn.case/id
                                                                                                                   :cmmn.case/name]}}]}])`

Throws an Exception:

`
Call to edn-query-language.core/query->ast did not conform to spec:
                            core.cljc:542
                            
                            -- Spec failed --------------------
                            
                            Function arguments
                            
                              ({:nexus.case.image-annotation/id
                                [:nexus.case.test-case/id :cmmn.case/id :cmmn.case/name],
                                :nexus.case.test-case/id
                                [:nexus.case.test-case/id :cmmn.case/id :cmmn.case/name]})
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            
                            should satisfy                            
                              vector?
                            
                            or                            
                              nil?`

Root cause probably:
https://github.com/wilkerlucio/pathom/blob/a24ad60a3936dd7a93c7c18ee9d5a390ed03db0d/src/com/wsscode/pathom/core.cljc#L542

What do you think?

**Comment by wilkerlucio** [comment] 2020-10-19 18:55
I can't reproduce this case, can you send a fully reproducible example?

I tried to get close, but got something that works:

```clojure
(pc/defresolver input-group=>cases-union
  [_ {:nexus.project/keys     [historic-cases]
      :nexus.input-group/keys [id] :as input}]
  {::pc/docstring "Resolve Cases by InputGroup, union query."
   ::pc/input     #{:nexus.input-group/id
                    :nexus.project/historic-cases}
   ::pc/output    [{:nexus.input-group/cases-union [:nexus.case.image-annotation/id
                                                    :nexus.case.test-case/id]}]}
  {:nexus.input-group/cases-union {:nexus.case.image-annotation/id 1}})

(def debug-parser
  (p/parallel-parser
    {::p/env     {::p/reader               [p/map-reader
                                            pc/parallel-reader
                                            pc/open-ident-reader
                                            p/env-placeholder-reader]
                  ::p/placeholder-prefixes #{">"}}
     ::p/mutate  pc/mutate-async
     ::p/plugins [(pc/connect-plugin {::pc/register [input-group=>cases-union
                                                     (pc/constantly-resolver :nexus.project/historic-cases "foo")]})
                  p/error-handler-plugin
                  p/trace-plugin]}))

(comment
  (async/<!! (debug-parser {}
     [{[:nexus.input-group/id 1]
       [{:nexus.input-group/cases-union {:nexus.case.image-annotation/id [:nexus.case.image-annotation/id
                                                                          :cmmn.case/id
                                                                          :cmmn.case/name]
                                         :nexus.case.test-case/id        [:nexus.case.test-case/id
                                                                          :cmmn.case/id
                                                                          :cmmn.case/name]}}]}])))
```

**Comment by tmoerman** [comment] 2020-10-19 19:18
I think this reproduces the problem:

```
(defresolver input-group=>cases-union [_ {:nexus.project/keys     [historic-cases]
                                          :nexus.input-group/keys [id] :as input}]
  {::pc/docstring "Resolve Cases by InputGroup, union query."
   ::pc/input     #{:nexus.input-group/id
                    :nexus.project/historic-cases}
   ::pc/output    [{:nexus.input-group/cases-union [:nexus.case.image-annotation/id
                                                    :nexus.case.test-case/id]}]}

  ;; Example by Wilker works:
  ;; {:nexus.input-group/cases-union {:nexus.case.image-annotation/id 1}}

  ;; to-many relationship doesn't work:
  {:nexus.input-group/cases-union [{:nexus.case.image-annotation/id 1}
                                   {:nexus.case.test-case/id 2}]})
```

Testing like this:
```
(let [debug-parser (p/parallel-parser
                     {::p/env     {::p/reader               [p/map-reader
                                                             pc/parallel-reader
                                                             pc/open-ident-reader
                                                             p/env-placeholder-reader]
                                   ::p/placeholder-prefixes #{">"}}
                      ::p/mutate  pc/mutate-async
                      ::p/plugins [(pc/connect-plugin {::pc/register [rslvrs/input-group=>cases-union
                                                                      (pc/constantly-resolver :nexus.project/historic-cases "foo")]})
                                   p/error-handler-plugin
                                   p/trace-plugin]})

      query        [{[:nexus.input-group/id 1] [{:nexus.input-group/cases-union {:nexus.case.image-annotation/id [:nexus.case.image-annotation/id]
                                                                                 :nexus.case.test-case/id        [:nexus.case.test-case/id]}}]}]]
  (async/<!! (debug-parser {} query)))
```
Produces the error:

```
{[:nexus.input-group/id 1]
 #:nexus.input-group{:cases-union
                     :com.wsscode.pathom.core/reader-error},
 :com.wsscode.pathom.core/errors
 {[[:nexus.input-group/id 1] :nexus.input-group/cases-union]
  "class clojure.lang.ExceptionInfo: Call to edn-query-language.core/query->ast did not conform to spec:
core.cljc:542

-- Spec failed
```

**Comment by tmoerman** [comment] 2020-10-19 20:44
Leaving a note here should anyone else run into the problem above:
The error happened because I was using an older version of **kaocha test-runner** in my project (I started from the Fulcro template project). Upgrading to version `1.0.700` from `0.0-601` made the error disappear, the union query resolver behaves correctly.

Big thanks for @wilkerlucio for helping me out in finding the problem!
