### ISSUE TITLE
Connect bug?

### ISSUE THREAD

**Issue by archaic** [wilkerlucio/pathom#192] opened 2021-04-29 07:07 UTC
Hi, a minimal example, on commit #5c5f6baae98f9cb7c7f76da09b903e17ff67482b:

`(defresolver get-number-and-bar-id
  [{:foo/keys [id]}]
  
  {:foo/number 1
   :bar/id "8e6c108c"})

(defresolver get-year
  [{:bar/keys [id]}]

  {:bar/year 2021})

(defresolver get-bar-id-from-year
  [{:bar/keys [year]}]
  
  {:bar/id "8e6c108c"})

(p.eql/process (pci/register [get-number-and-bar-id
                                get-year
                                get-bar-id-from-year])
                 [{[:foo/id "e55373a1"] [:foo/number :bar/id :bar/year]}])
`
=> {[:foo/id "e55373a1"] {:foo/number 1, :bar/id "8e6c108c"}} 
Where is :bar/year ?

**Comment by wilkerlucio** [comment] 2021-04-29 13:44
Hello @archaic, thanks for the report. Just one thing, for Pathom 3 you should use the Pathom 3 repo: https://github.com/wilkerlucio/pathom3

Other than that, the issue is fixed on master by https://github.com/wilkerlucio/pathom3/pull/43

**Closed by wilkerlucio** 2021-04-29 13:44 UTC
